name: CI Phase 1 - Basic Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      Image_used2: ${{steps.set_tag.outputs.Image_tag}}
    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Dockerversion
        run: docker --version

      - name: Set Image_tag
        id: set_tag
        run: |
          TAG=${GITHUB_SHA::7}
          echo "Image_tag=$TAG" >> $GITHUB_OUTPUT


      - name: Build Docker Image
        run: docker build -t iris-app:${{steps.set_tag.outputs.Image_tag}} .

      - name: Build Docker Image created successfully
        id: build-image
        run: docker build -t iris-app:${{steps.set_tag.outputs.Image_tag}} .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: list docker images
        run:  "Image builded in build ${{needs.build.outputs.Image_used2}}"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Get the output from the build job
        run: echo "Image used in build job is ${{needs.build.outputs.Image_used2}}"
