name: CI Phase 1 - Basic Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      Image_used: ${{steps.set_tag.outputs.Image_tag}}
    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Dockerversion
        run: docker --version

      - name: Set Image_tag
        id: set_tag
        run: |
          TAG=${GITHUB_SHA::7}
          echo "image_tag=$TAG" >> $GITHUB_OUTPUT


      - name: Build Docker Image
        run: docker build -t ${Image_tag} .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: list docker images
        run: docker images | grep "${{needs.build.outputs.Image_used}}"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Get the output from the build job
        run: echo "Image used in build job is ${{needs.build.outputs.Image_used}}"

