name: CI Phase 1 - Basic Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Dockerversion
        run: docker --version

      - name: list all the filed in current directory
        run: ls -la
      - name: Build Docker Image
        run: docker build -t test-app:${{ github.sha }} .

      - name: Print success message
        run: echo "Build successful!"

