name: CI Phase 1 - Basic Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout COde
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: Dockerversion
        run: docker --version

      - name: Set Image_tag
        run: echo "Image_tag=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: list docker images
        run: docker images

      - name: Build Docker Image
        run: docker build -t ${Image_tag} .

      - name: Print success message
        run: echo "Build successful!"

